//! The rules-preserving symmetry group of Check4, for the solver's state
//! space reduction (the "/8" in the handoff's estimate).
//!
//! Pawns move along the y axis, so board rotations and diagonal mirrors do
//! **not** preserve the rules. What survives is the group generated by
//! three commuting involutions — `(Z/2)^3`, 8 elements:
//!
//! - **mirror_x** — `x -> 3 - x`. Nothing else changes.
//! - **mirror_y** — `y -> 3 - y`, and both pawns' facing directions flip
//!   (the "reach row 0/3, face up/down" rule mirrors with them).
//! - **swap_players** — the two sides trade pieces; the turn and winner
//!   swap with them. Pawn directions travel with their pawns unchanged
//!   (a direction is piece state, not a player convention).
//!
//! Every element is its own inverse and the generators commute, so
//! composition is just XOR of the three flags.
//!
//! The group is **equivariant with play**: transforming a position and
//! then making the transformed move lands on the transform of the original
//! result, and legal-move sets map bijectively. The tests verify this
//! against the engine over seeded random games.
//!
//! [`Game::canonical_pack`] reduces a position to its orbit representative
//! (minimum [`Game::pack`] over the 8 transforms) — two positions get the
//! same value iff they are the same position up to symmetry.

use crate::game::{piece_index, Direction, Game, Move, PieceKind, Player};

/// One element of the 8-element symmetry group. Three commuting involutive
/// flags; the identity is `Transform::default()` (all flags off).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Transform {
    /// Mirror the board left-right (`x -> 3 - x`).
    pub mirror_x: bool,
    /// Mirror the board top-bottom (`y -> 3 - y`), flipping both pawns'
    /// facing directions.
    pub mirror_y: bool,
    /// Swap the two players: pieces, turn, winner.
    pub swap_players: bool,
}

impl Transform {
    /// All 8 group elements, identity first.
    pub const ALL: [Transform; 8] = {
        let mut all = [Transform {
            mirror_x: false,
            mirror_y: false,
            swap_players: false,
        }; 8];
        let mut i = 0;
        while i < 8 {
            all[i] = Transform {
                mirror_x: i & 1 != 0,
                mirror_y: i & 2 != 0,
                swap_players: i & 4 != 0,
            };
            i += 1;
        }
        all
    };

    /// Group composition: apply `self`, then `other`. The generators
    /// commute and are involutions, so this is XOR — and every element is
    /// its own [`inverse`](Transform::inverse).
    #[must_use]
    pub fn compose(self, other: Transform) -> Transform {
        Transform {
            mirror_x: self.mirror_x ^ other.mirror_x,
            mirror_y: self.mirror_y ^ other.mirror_y,
            swap_players: self.swap_players ^ other.swap_players,
        }
    }

    /// The inverse element (every element of this group is an involution,
    /// so this is the identity function; it exists for readable call
    /// sites).
    #[must_use]
    pub fn inverse(self) -> Transform {
        self
    }

    fn coord(self, (x, y): (u8, u8)) -> (u8, u8) {
        (
            if self.mirror_x { 3 - x } else { x },
            if self.mirror_y { 3 - y } else { y },
        )
    }

    fn player(self, player: Player) -> Player {
        if self.swap_players {
            player.opponent()
        } else {
            player
        }
    }

    fn direction(self, dir: Direction) -> Direction {
        match (self.mirror_y, dir) {
            (false, dir) => dir,
            (true, Direction::Up) => Direction::Down,
            (true, Direction::Down) => Direction::Up,
        }
    }

    /// Transform a move so it plays the same role in the transformed
    /// position.
    #[must_use]
    pub fn apply_move(self, mv: Move) -> Move {
        let (x, y) = self.coord((mv.x, mv.y));
        Move {
            player: self.player(mv.player),
            piece: mv.piece,
            x,
            y,
        }
    }

    /// Transform a position. `turn_count` is preserved unchanged.
    #[must_use]
    pub fn apply(self, game: &Game) -> Game {
        let mut out = game.clone();

        for player in [Player::One, Player::Two] {
            for kind in PieceKind::ALL {
                let src = game.pieces[piece_index(player, kind)];
                let dst = &mut out.pieces[piece_index(self.player(player), kind)];
                dst.pos = src.pos.map(|c| self.coord(c));
                dst.prev = src.prev.map(|c| self.coord(c));
            }
        }

        for player in [Player::One, Player::Two] {
            let dir = game.pawn_dirs[(player.number() - 1) as usize];
            out.pawn_dirs[(self.player(player).number() - 1) as usize] = self.direction(dir);
        }

        out.turn = self.player(game.turn);
        out.winner = game.winner.map(|w| self.player(w));
        out
    }
}

impl Game {
    /// The position's orbit representative: the minimum [`Game::pack`]
    /// value over the 8 symmetry transforms. Two positions canonicalize
    /// equally iff one is a symmetry image of the other, so this is the
    /// key to deduplicate the solver's state space by (~/8 away from the
    /// mirror-fixed positions).
    ///
    /// Inherits [`Game::pack`]'s caveats: `turn_count` and a
    /// forfeit-declared winner are not represented.
    #[must_use]
    pub fn canonical_pack(&self) -> u128 {
        Transform::ALL
            .iter()
            .map(|t| t.apply(self).pack())
            .min()
            .expect("the group is not empty")
    }
}
