//! Gotcha-semantics tests. The state-key checkpoints asserted inline below
//! were generated by scripting the same move sequences through the
//! normative TypeScript engine.

use check4_core::{Direction, Game, GameSetup, Move, MoveError, PieceKind, Player, SetupError};

fn mv(player: Player, piece: PieceKind, x: u8, y: u8) -> Move {
    Move {
        player,
        piece,
        x,
        y,
    }
}

/// The scripted game from golden-semantics.txt, checked key by key.
#[test]
fn golden_semantics_scripted_game() {
    let mut g = Game::new();
    assert_eq!(
        g.state_key(),
        "t1|w-|----,----,----,----,u|----,----,----,----,d"
    );

    // P1 pawn drops on row 3: direction flips to down.
    g.take_turn(mv(Player::One, PieceKind::Pawn, 1, 3)).unwrap();
    assert_eq!(
        g.state_key(),
        "t2|w-|13--,----,----,----,d|----,----,----,----,d"
    );

    // P2 pawn drops on row 0: direction flips to up.
    g.take_turn(mv(Player::Two, PieceKind::Pawn, 2, 0)).unwrap();
    assert_eq!(
        g.state_key(),
        "t1|w-|13--,----,----,----,d|20--,----,----,----,u"
    );

    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 0)).unwrap();
    assert_eq!(
        g.state_key(),
        "t2|w-|13--,00--,----,----,d|20--,----,----,----,u"
    );

    g.take_turn(mv(Player::Two, PieceKind::Knight, 3, 3))
        .unwrap();
    assert_eq!(
        g.state_key(),
        "t1|w-|13--,00--,----,----,d|20--,----,----,33--,u"
    );

    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 2)).unwrap();
    assert_eq!(
        g.state_key(),
        "t2|w-|13--,0200,----,----,d|20--,----,----,33--,u"
    );

    // P1's rook back to (0,0) is invalid here (not P1's turn).
    assert!(!g.move_is_valid(mv(Player::One, PieceKind::Rook, 0, 0)));

    g.take_turn(mv(Player::Two, PieceKind::Knight, 1, 2))
        .unwrap();
    assert_eq!(
        g.state_key(),
        "t1|w-|13--,0200,----,----,d|20--,----,----,1233,u"
    );

    // Now it is P1's turn and the same move is a backtrack.
    assert!(!g.move_is_valid(mv(Player::One, PieceKind::Rook, 0, 0)));

    // Rook captures the knight: the knight returns to the gutter with its
    // move memory wiped.
    g.take_turn(mv(Player::One, PieceKind::Rook, 1, 2)).unwrap();
    assert_eq!(
        g.state_key(),
        "t2|w-|13--,1202,----,----,d|20--,----,----,----,u"
    );
    assert_eq!(g.piece_position(Player::Two, PieceKind::Knight), None);
    assert_eq!(g.piece_prev(Player::Two, PieceKind::Knight), None);

    // The captured knight may re-drop.
    assert!(g.move_is_valid(mv(Player::Two, PieceKind::Knight, 3, 3)));
    g.take_turn(mv(Player::Two, PieceKind::Knight, 3, 3))
        .unwrap();
    assert_eq!(
        g.state_key(),
        "t1|w-|13--,1202,----,----,d|20--,----,----,33--,u"
    );
}

/// The WIN checkpoint from golden-semantics.txt, reached by play: after the
/// winning move the key shows the opponent to move (t2|w1) and no legal
/// moves remain.
#[test]
fn golden_semantics_win_state() {
    let mut g = Game::new();
    g.take_turn(mv(Player::One, PieceKind::Pawn, 0, 1)).unwrap();
    g.take_turn(mv(Player::Two, PieceKind::Pawn, 0, 2)).unwrap();
    g.take_turn(mv(Player::One, PieceKind::Rook, 1, 1)).unwrap();
    g.take_turn(mv(Player::Two, PieceKind::Rook, 1, 2)).unwrap();
    g.take_turn(mv(Player::One, PieceKind::Bishop, 2, 1))
        .unwrap();
    g.take_turn(mv(Player::Two, PieceKind::Bishop, 2, 2))
        .unwrap();
    // Completes P1's row y=1.
    g.take_turn(mv(Player::One, PieceKind::Knight, 3, 1))
        .unwrap();

    assert_eq!(
        g.state_key(),
        "t2|w1|01--,11--,21--,31--,u|02--,12--,22--,----,d"
    );
    assert_eq!(g.winner(), Some(Player::One));
    assert_eq!(g.turn(), Player::Two);
    assert_eq!(g.turn_count(), 7);
    assert!(g.legal_moves().is_empty());
    assert_eq!(
        g.take_turn(mv(Player::Two, PieceKind::Pawn, 0, 1)),
        Err(MoveError::GameOver)
    );
}

/// The same WIN state built from arbitrary placements instead of play.
#[test]
fn from_setup_reproduces_win_state() {
    let mut setup = GameSetup::empty(Player::Two);
    setup.winner = Some(Player::One);
    setup.turn_count = 7;
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((0, 1));
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((1, 1));
    setup.piece_mut(Player::One, PieceKind::Bishop).pos = Some((2, 1));
    setup.piece_mut(Player::One, PieceKind::Knight).pos = Some((3, 1));
    setup.piece_mut(Player::Two, PieceKind::Pawn).pos = Some((0, 2));
    setup.piece_mut(Player::Two, PieceKind::Rook).pos = Some((1, 2));
    setup.piece_mut(Player::Two, PieceKind::Bishop).pos = Some((2, 2));

    let g = Game::from_setup(&setup).unwrap();
    assert_eq!(
        g.state_key(),
        "t2|w1|01--,11--,21--,31--,u|02--,12--,22--,----,d"
    );
    assert_eq!(g.turn_count(), 7);
    assert!(g.legal_moves().is_empty());
}

/// An off-turn move is rejected as such even when it would otherwise be
/// perfectly legal — the fuzz drivers only ever construct on-turn moves,
/// so this rule is invisible to the differential net.
#[test]
fn off_turn_moves_are_rejected() {
    let mut g = Game::new();
    let p2_drop = mv(Player::Two, PieceKind::Knight, 2, 2);

    assert_eq!(g.take_turn(p2_drop).unwrap_err(), MoveError::NotYourTurn);
    assert!(!g.move_is_valid(p2_drop));

    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 0)).unwrap();
    assert!(g.move_is_valid(p2_drop));
    g.take_turn(p2_drop).unwrap();
    assert_eq!(
        g.piece_position(Player::Two, PieceKind::Knight),
        Some((2, 2))
    );
}

/// Out-of-range coordinates are rejected at the API boundary — also
/// invisible to the fuzz net, which only enumerates 0..=3.
#[test]
fn out_of_bounds_coordinates_are_rejected() {
    let mut g = Game::new();
    for (x, y) in [(4, 0), (0, 4), (4, 4), (255, 1)] {
        let bad = mv(Player::One, PieceKind::Rook, x, y);
        assert_eq!(g.take_turn(bad).unwrap_err(), MoveError::OutOfBounds);
        assert!(!g.move_is_valid(bad));
    }
}

/// A pawn landing on the middle rows keeps its direction; only rows 0
/// and 3 reorient it.
#[test]
fn pawn_keeps_direction_on_middle_rows() {
    let mut g = Game::new();
    g.take_turn(mv(Player::One, PieceKind::Pawn, 0, 1)).unwrap();
    assert_eq!(g.pawn_direction(Player::One), Direction::Up);

    g.take_turn(mv(Player::Two, PieceKind::Rook, 3, 3)).unwrap();

    // Up-facing pawn advances onto row 2 and must NOT flip.
    g.take_turn(mv(Player::One, PieceKind::Pawn, 0, 2)).unwrap();
    assert_eq!(g.pawn_direction(Player::One), Direction::Up);
}

/// Forfeit ends the game exactly like the TS engine: the loser's opponent
/// wins, no further moves exist, and (matching TS, which has no game-over
/// guard in forfeit) a forfeit on a finished game overwrites the winner.
#[test]
fn forfeit_ends_the_game() {
    let mut g = Game::new();
    g.forfeit(None); // player to move (P1) loses
    assert_eq!(g.winner(), Some(Player::Two));
    assert_eq!(
        g.state_key(),
        "t1|w2|----,----,----,----,u|----,----,----,----,d"
    );
    assert!(g.legal_moves().is_empty());
    assert_eq!(
        g.take_turn(mv(Player::One, PieceKind::Pawn, 0, 0))
            .unwrap_err(),
        MoveError::GameOver
    );

    let mut g = Game::new();
    g.forfeit(Some(Player::Two));
    assert_eq!(g.winner(), Some(Player::One));

    g.forfeit(Some(Player::One));
    assert_eq!(g.winner(), Some(Player::Two));
}

#[test]
fn from_setup_validates_coordinates() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((4, 0));
    assert_eq!(
        Game::from_setup(&setup).unwrap_err(),
        SetupError::CoordinateOutOfBounds {
            piece_index: 1,
            coord: (4, 0)
        }
    );

    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::Two, PieceKind::Pawn).prev = Some((0, 7));
    assert_eq!(
        Game::from_setup(&setup).unwrap_err(),
        SetupError::CoordinateOutOfBounds {
            piece_index: 4,
            coord: (0, 7)
        }
    );
}

#[test]
fn pawn_direction_flips_on_drop_at_far_rows() {
    // P1 pawn starts up; dropping on row 3 flips it down.
    let mut g = Game::new();
    assert_eq!(g.pawn_direction(Player::One), Direction::Up);
    g.take_turn(mv(Player::One, PieceKind::Pawn, 2, 3)).unwrap();
    assert_eq!(g.pawn_direction(Player::One), Direction::Down);

    // P2 pawn starts down; dropping on row 0 flips it up.
    assert_eq!(g.pawn_direction(Player::Two), Direction::Down);
    g.take_turn(mv(Player::Two, PieceKind::Pawn, 2, 0)).unwrap();
    assert_eq!(g.pawn_direction(Player::Two), Direction::Up);

    // Dropping on a middle row leaves the direction alone.
    let mut g = Game::new();
    g.take_turn(mv(Player::One, PieceKind::Pawn, 2, 1)).unwrap();
    assert_eq!(g.pawn_direction(Player::One), Direction::Up);
}

#[test]
fn capture_wipes_memory_and_vacated_square_accepts_redrop() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((0, 0));
    let knight = setup.piece_mut(Player::Two, PieceKind::Knight);
    knight.pos = Some((0, 3));
    knight.prev = Some((1, 1));
    setup.piece_mut(Player::Two, PieceKind::Rook).pos = Some((3, 0));
    let mut g = Game::from_setup(&setup).unwrap();

    // P1 rook captures the knight on (0,3): back to the gutter, memory wiped.
    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 3)).unwrap();
    assert_eq!(g.piece_position(Player::Two, PieceKind::Knight), None);
    assert_eq!(g.piece_prev(Player::Two, PieceKind::Knight), None);

    // While (0,3) is occupied by the capturer, the knight cannot drop there.
    assert!(!g.move_is_valid(mv(Player::Two, PieceKind::Knight, 0, 3)));
    g.take_turn(mv(Player::Two, PieceKind::Rook, 3, 1)).unwrap();

    // The capturer vacates the square...
    g.take_turn(mv(Player::One, PieceKind::Rook, 3, 3)).unwrap();

    // ...and the captured knight may re-drop exactly where it was taken.
    assert!(g.move_is_valid(mv(Player::Two, PieceKind::Knight, 0, 3)));
    g.take_turn(mv(Player::Two, PieceKind::Knight, 0, 3))
        .unwrap();
    assert_eq!(
        g.piece_position(Player::Two, PieceKind::Knight),
        Some((0, 3))
    );
    // A drop remembers the gutter: no square is forbidden to it.
    assert_eq!(g.piece_prev(Player::Two, PieceKind::Knight), None);
}

#[test]
fn backtrack_is_rejected_and_memory_is_one_square_deep() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((0, 0));
    let mut g = Game::from_setup(&setup).unwrap();

    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 2)).unwrap();
    assert_eq!(g.piece_prev(Player::One, PieceKind::Rook), Some((0, 0)));
    g.take_turn(mv(Player::Two, PieceKind::Rook, 3, 0)).unwrap();

    // Straight back to (0,0) is a backtrack; a different square is fine.
    assert_eq!(
        g.take_turn(mv(Player::One, PieceKind::Rook, 0, 0)),
        Err(MoveError::Backtrack)
    );
    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 3)).unwrap();
    g.take_turn(mv(Player::Two, PieceKind::Rook, 3, 1)).unwrap();

    // The memory overwrote: (0,2) is now forbidden, (0,0) is legal again.
    assert_eq!(
        g.take_turn(mv(Player::One, PieceKind::Rook, 0, 2)),
        Err(MoveError::Backtrack)
    );
    g.take_turn(mv(Player::One, PieceKind::Rook, 0, 0)).unwrap();
}

#[test]
fn rook_and_bishop_paths_block_but_knight_jumps() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((0, 0));
    setup.piece_mut(Player::One, PieceKind::Bishop).pos = Some((3, 0));
    setup.piece_mut(Player::One, PieceKind::Knight).pos = Some((1, 0));
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((0, 1));
    setup.piece_mut(Player::Two, PieceKind::Pawn).pos = Some((2, 1));
    let g = Game::from_setup(&setup).unwrap();

    // Rook (0,0) -> (0,2) is blocked by its own pawn on (0,1).
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Rook, 0, 2)),
        Err(MoveError::PathBlocked {
            piece: PieceKind::Rook
        })
    );
    // Landing on the blocker is self-capture, not a jump.
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Rook, 0, 1)),
        Err(MoveError::SelfCapture)
    );

    // Bishop (3,0) -> (1,2) is blocked by the enemy pawn on (2,1)...
    assert_eq!(
        g.clone()
            .take_turn(mv(Player::One, PieceKind::Bishop, 1, 2)),
        Err(MoveError::PathBlocked {
            piece: PieceKind::Bishop
        })
    );
    // ...but capturing the blocker itself is legal.
    assert!(g.move_is_valid(mv(Player::One, PieceKind::Bishop, 2, 1)));

    // The knight jumps over everything: (1,0) -> (0,2) leaps the pawns.
    assert!(g.move_is_valid(mv(Player::One, PieceKind::Knight, 0, 2)));
}

#[test]
fn pawn_captures_diagonally_only_and_advances_straight_only() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((1, 1));
    setup.piece_mut(Player::Two, PieceKind::Pawn).pos = Some((1, 2));
    setup.piece_mut(Player::Two, PieceKind::Rook).pos = Some((0, 2));
    let g = Game::from_setup(&setup).unwrap();

    // Straight ahead onto an enemy: pawns cannot capture forward.
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Pawn, 1, 2)),
        Err(MoveError::IllegalPieceMove {
            piece: PieceKind::Pawn,
            x: 1,
            y: 2
        })
    );
    // Diagonal onto an empty square: pawns only go diagonal to capture.
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Pawn, 2, 2)),
        Err(MoveError::IllegalPieceMove {
            piece: PieceKind::Pawn,
            x: 2,
            y: 2
        })
    );
    // Diagonal capture is legal.
    assert!(g.move_is_valid(mv(Player::One, PieceKind::Pawn, 0, 2)));
    // Sideways and backwards are never legal.
    assert!(!g.move_is_valid(mv(Player::One, PieceKind::Pawn, 0, 1)));
    assert!(!g.move_is_valid(mv(Player::One, PieceKind::Pawn, 1, 0)));

    // Straight ahead onto an empty square is legal once the enemy is gone.
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((1, 1));
    let g = Game::from_setup(&setup).unwrap();
    assert!(g.move_is_valid(mv(Player::One, PieceKind::Pawn, 1, 2)));
}

#[test]
fn win_detected_on_row_column_and_both_diagonals() {
    // Three pre-placed squares plus the knight-drop square that completes
    // the line.
    type WinLine = ([(u8, u8); 3], (u8, u8));

    let lines: [WinLine; 4] = [
        ([(0, 2), (1, 2), (2, 2)], (3, 2)), // row y=2
        ([(1, 0), (1, 1), (1, 2)], (1, 3)), // column x=1
        ([(0, 0), (1, 1), (2, 2)], (3, 3)), // diagonal x-y=0
        ([(0, 3), (1, 2), (2, 1)], (3, 0)), // anti-diagonal x+y=3
    ];

    for (placed, drop) in lines {
        let mut setup = GameSetup::empty(Player::One);
        setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some(placed[0]);
        setup.piece_mut(Player::One, PieceKind::Rook).pos = Some(placed[1]);
        setup.piece_mut(Player::One, PieceKind::Bishop).pos = Some(placed[2]);
        let mut g = Game::from_setup(&setup).unwrap();

        g.take_turn(mv(Player::One, PieceKind::Knight, drop.0, drop.1))
            .unwrap();
        assert_eq!(g.winner(), Some(Player::One), "line through {placed:?}");
        assert_eq!(g.turn(), Player::Two, "turn flips before the win check");
        assert!(g.legal_moves().is_empty());
    }

    // Three in line with the fourth in the gutter is not a win.
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((0, 2));
    setup.piece_mut(Player::One, PieceKind::Rook).pos = Some((1, 2));
    setup.piece_mut(Player::One, PieceKind::Bishop).pos = Some((2, 2));
    let mut g = Game::from_setup(&setup).unwrap();
    g.take_turn(mv(Player::One, PieceKind::Knight, 0, 0))
        .unwrap();
    assert_eq!(g.winner(), None);
}

#[test]
fn gutter_drops_require_an_empty_square() {
    let mut setup = GameSetup::empty(Player::One);
    setup.piece_mut(Player::One, PieceKind::Pawn).pos = Some((2, 2));
    setup.piece_mut(Player::Two, PieceKind::Pawn).pos = Some((1, 1));
    let g = Game::from_setup(&setup).unwrap();

    // Onto an enemy piece: no capturing from the gutter.
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Rook, 1, 1)),
        Err(MoveError::GutterDropOnOccupiedSquare)
    );
    // Onto an own piece: same rule.
    assert_eq!(
        g.clone().take_turn(mv(Player::One, PieceKind::Rook, 2, 2)),
        Err(MoveError::GutterDropOnOccupiedSquare)
    );
    // Any empty square is fine.
    assert!(g.move_is_valid(mv(Player::One, PieceKind::Rook, 0, 3)));
}

#[test]
fn forfeit_awards_the_opponent() {
    let mut g = Game::new();
    g.forfeit(None); // P1 is to move, so P1 loses.
    assert_eq!(g.winner(), Some(Player::Two));
    assert!(g.state_key().starts_with("t1|w2|"));

    let mut g = Game::new();
    g.forfeit(Some(Player::Two));
    assert_eq!(g.winner(), Some(Player::One));
}
